### ISSUE TITLE
Idea to add styles to components?

### ISSUE THREAD

**Issue by bitbaggi** [LayZeeDK/ngx-ivy-zippy-elements-without-platform-and-ngzone#1]
Hello,

i've tried to add styles to the component like 
`@Component({
  encapsulation: ViewEncapsulation.ShadowDom,
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'test',
  template: '<div class="test"><ng-content></ng-content></div>',
  styles: [':host {background-color: red} .test{background-color: blue}']
})
export class ButtonComponent {
}`

but the style is not applied to component, nor to the div with class test.

Do i need zone.js for that?
Or anything other is wrong in this example?

**Comment by LayZeeDK** [comment]
This is a failed experiment that I abandoned. I can't get Shadow DOM or content projection working without further reverse-engineering and hacking of `createCustomElement`.

**Comment by LayZeeDK** [comment]
You can try this out, @bitbaggi:
https://twitter.com/codingnuclei/status/1237801300198412288
